# 服务端IP和端口
SERVER:
  HOST: 0.0.0.0
  PORT: 8080

# 微信小程序
WEIXIN:
  APPID: xxxxxx
  SECRET: xxxxxx

# 数据库
MYSQL:
  HOST: localhost
  PORT: 3306
  DATABASE: epidemic_control
  USERNAME: ec
  PASSWORD: 123456

# 日志
LOG:
  # 日志等级：CRITICAL > ERROR > WARNING > INFO > DEBUG > NOTSET
  LEVEL: DEBUG
  # 输出目标：console file
  OUTPUT: file
  # 若输出到文件，配置日志文件所在目录
  DIR: ./logs/
  # 日志文件的最大字节数
  MAX_BYTES: 104857600 # 100 * 1024 * 1024
