"""empty message

Revision ID: 54ff6ee01b08
Revises: 9a13caa9d1c7
Create Date: 2022-05-09 10:42:34.193275

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '54ff6ee01b08'
down_revision = '9a13caa9d1c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('role1', sa.Enum('common', 'admin', name='role'), nullable=True, comment='角色。1代表普通成员，2代表管理员。'))
    op.drop_column('member', 'role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('role', mysql.ENUM('admin', charset='utf8mb4', collation='utf8mb4_0900_ai_ci'), nullable=True, comment='角色。1代表普通成员，2代表管理员。'))
    op.drop_column('member', 'role1')
    # ### end Alembic commands ###
