"""empty message

Revision ID: 89f877001cf0
Revises: 5b189b96fa64
Create Date: 2022-05-09 10:35:13.970725

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '89f877001cf0'
down_revision = '5b189b96fa64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('role1', sa.Enum('admin', name='role'), nullable=True, comment='角色。1代表普通成员，2代表管理员。'))
    op.drop_column('member', 'role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('role', mysql.VARCHAR(length=20), nullable=True, comment='角色。1代表普通成员，2代表管理员。'))
    op.drop_column('member', 'role1')
    # ### end Alembic commands ###
