"""empty message

Revision ID: 9a13caa9d1c7
Revises: 89f877001cf0
Create Date: 2022-05-09 10:36:03.353104

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9a13caa9d1c7'
down_revision = '89f877001cf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('role', sa.Enum('admin', name='role'), nullable=True, comment='角色。1代表普通成员，2代表管理员。'))
    op.drop_column('member', 'role1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('role1', mysql.ENUM('admin'), nullable=True, comment='角色。1代表普通成员，2代表管理员。'))
    op.drop_column('member', 'role')
    # ### end Alembic commands ###
