"""empty message

Revision ID: be61f72de3ed
Revises: f582e149585c
Create Date: 2022-04-24 23:54:15.991103

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'be61f72de3ed'
down_revision = 'f582e149585c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'))
    op.add_column('member', sa.Column('update_time', sa.DateTime(), nullable=True, comment='修改时间'))
    op.drop_column('member', 'updatetime')
    op.drop_column('member', 'createtime')
    op.add_column('organization', sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'))
    op.add_column('organization', sa.Column('update_time', sa.DateTime(), nullable=True, comment='修改时间'))
    op.drop_column('organization', 'updatetime')
    op.drop_column('organization', 'createtime')
    op.add_column('user', sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'))
    op.drop_column('user', 'createtime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('createtime', mysql.DATETIME(), nullable=True, comment='创建时间'))
    op.drop_column('user', 'create_time')
    op.add_column('organization', sa.Column('createtime', mysql.DATETIME(), nullable=True, comment='创建时间'))
    op.add_column('organization', sa.Column('updatetime', mysql.DATETIME(), nullable=True, comment='修改时间'))
    op.drop_column('organization', 'update_time')
    op.drop_column('organization', 'create_time')
    op.add_column('member', sa.Column('createtime', mysql.DATETIME(), nullable=True, comment='创建时间'))
    op.add_column('member', sa.Column('updatetime', mysql.DATETIME(), nullable=True, comment='修改时间'))
    op.drop_column('member', 'update_time')
    op.drop_column('member', 'create_time')
    # ### end Alembic commands ###
