"""empty message

Revision ID: cc995414df73
Revises: 248ce6b4d460
Create Date: 2022-05-09 22:27:10.565156

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cc995414df73'
down_revision = '248ce6b4d460'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization', sa.Column('type', mysql.VARCHAR(length=10), nullable=True, comment='类型。1代表社区，2代表学校。'))
    # ### end Alembic commands ###
