"""empty message

Revision ID: dcd25fceb321
Revises: 19f869534792
Create Date: 2022-05-07 21:23:34.017082

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dcd25fceb321'
down_revision = '19f869534792'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('member', 'role',
               existing_type=mysql.VARCHAR(length=20),
               comment='角色。1代表普通成员，2代表管理员',
               existing_comment='角色。1代表普通成员，2代表管理员。',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('member', 'role',
               existing_type=mysql.VARCHAR(length=20),
               comment='角色。1代表普通成员，2代表管理员。',
               existing_comment='角色。1代表普通成员，2代表管理员',
               existing_nullable=True)
    # ### end Alembic commands ###
