"""empty message

Revision ID: e35e124ff488
Revises: be61f72de3ed
Create Date: 2022-05-01 11:28:01.637649

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e35e124ff488'
down_revision = 'be61f72de3ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('member_number', sa.String(length=100), nullable=True, comment='成员编号'))
    op.add_column('member', sa.Column('family_members_count', sa.Integer(), nullable=True, comment='家庭人数'))
    op.drop_column('member', 'number')
    op.drop_column('member', 'family_number')
    op.add_column('organization', sa.Column('avatar_url', sa.String(length=100), nullable=True, comment='头像URL'))
    op.drop_column('organization', 'member_number_example')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization', sa.Column('member_number_example', mysql.VARCHAR(length=100), nullable=True, comment='成员编号样例'))
    op.drop_column('organization', 'avatar_url')
    op.add_column('member', sa.Column('family_number', mysql.INTEGER(), autoincrement=False, nullable=True, comment='家庭人数'))
    op.add_column('member', sa.Column('number', mysql.VARCHAR(length=100), nullable=True, comment='编号'))
    op.drop_column('member', 'family_members_count')
    op.drop_column('member', 'member_number')
    # ### end Alembic commands ###
