"""empty message

Revision ID: f582e149585c
Revises: 98f2ff65316f
Create Date: 2022-04-24 22:44:55.902064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f582e149585c'
down_revision = '98f2ff65316f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=True, comment='类型。1代表社区，2代表学校。'),
    sa.Column('name', sa.String(length=60), nullable=True, comment='名称'),
    sa.Column('desc', sa.Text(), nullable=True, comment='简介'),
    sa.Column('contact', sa.String(length=20), nullable=True, comment='联系人'),
    sa.Column('contact_phone', sa.String(length=20), nullable=True, comment='联系人电话'),
    sa.Column('address', sa.String(length=100), nullable=True, comment='地址（省市县+详细地址）'),
    sa.Column('address_longitude', sa.Float(), nullable=True, comment='地址（经度）'),
    sa.Column('address_latitude', sa.Float(), nullable=True, comment='地址（维度）'),
    sa.Column('member_number_example', sa.String(length=100), nullable=True, comment='成员编号样例'),
    sa.Column('member_number_part', sa.String(length=20), nullable=True, comment="成员编号组成部分。1代表楼栋号，2代表单元号，3代表门牌号。若值为 '1,2,3' 表示成员编号由 楼栋号、单元号、门牌号 组成"),
    sa.Column('createtime', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updatetime', sa.DateTime(), nullable=True, comment='修改时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_name'), 'organization', ['name'], unique=True)
    op.create_table('member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=100), nullable=True, comment='编号'),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True, comment='角色。1代表普通成员，2代表管理员。'),
    sa.Column('name', sa.String(length=20), nullable=True, comment='姓名'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='电话'),
    sa.Column('family_number', sa.Integer(), nullable=True, comment='家庭人数'),
    sa.Column('family_others_name', sa.String(length=1000), nullable=True, comment="家庭其他成员姓名。多个姓名之间用逗号隔开，例如：'张三,李四'。"),
    sa.Column('createtime', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updatetime', sa.DateTime(), nullable=True, comment='修改时间'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('createtime', sa.DateTime(), nullable=True, comment='创建时间'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'createtime')
    op.drop_table('member')
    op.drop_index(op.f('ix_organization_name'), table_name='organization')
    op.drop_table('organization')
    # ### end Alembic commands ###
